<?php

namespace Erik\CRUDBundle\Repository;

/**
 * Workout1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Workout1Repository extends \Doctrine\ORM\EntityRepository
{
}
